### ISSUE TITLE
How to sort out and configure this project

### ISSUE THREAD

**Issue by malikhizar** [czxttkl/MetaData#9]
How to sort out and configure this project on a machine where originally it hasn't been created. As I want to _use this same code for clustering my own data_ i.e. of multi-typed objects. So the start up steps are not much clear to accomplish smooth running of code used in this project. 

Please provide **naive startup steps** (step by step) to configure the same project on a new machine where the original project hasn't been created. Please also provide the **tools and technologies** required to run these codes as well. Please also give the **data transformation steps** for the algorithm i.e. _if someone wants to shape her data that support this algorithm then how will she transform her data to the required form._

Thanking you in anticipation.

Regards!

**Comment by czxttkl** [comment]
Hi,

Sorry I guess the version on github may not work properly since we haven't
maintained it for a long time. My colleague may have a correct version. I
will ask him about it and then let you know.

Thanks,
Chen

**Comment by malikhizar** [comment]
Thanks Chen, I hope you'll arrange the correct working version as soon as possible as I was in search of it a long ago. So please do it for me, it'll be your gratitude.

Thanks,
Malik

**Comment by malikhizar** [comment]
Hi Dear Chen,

Hope you are doing fine. As I have requested you earlier about the original
version of EvoNetClus algorithm.
- Can you kindly provide me the original working version of the project
  with (How to Use & Configure) details so that I'll then be able to proceed
  further in my research work for my results using that algorithm ?
- How long will it take to trace the correct version ?
- Can you answer some of my questions about EvoNetClus algorithm?
- Can we arrange a half an hour meeting/discussion online on any forum
  regarding EvoNetClus algorithm?

I'll be much thankful and very grateful to you if you help me.

Thanks
Malik Khizar Hayat

On Wed, Apr 27, 2016 at 6:28 PM, Zhengxing Chen notifications@github.com
wrote:

> Hi,
> 
> Sorry I guess the version on github may not work properly since we haven't
> maintained it for a long time. My colleague may have a correct version. I
> will ask him about it and then let you know.
> 
> Thanks,
> Chen
> 
> On Wed, Apr 27, 2016 at 4:31 AM, khizer-hayat notifications@github.com
> wrote:
> 
> > How to sort out and configure this project on a machine where originally
> > it hasn't been created. As I want to use this same code for clustering my
> > own data i.e. of multi-typed objects. So the start up steps are not much
> > clear to accomplish smooth running of code used in this project.
> > 
> > Please provide a naive startup steps (step by step) to configure the same
> > project on a new machine where the original project hasn't been created.
> > And also provide the tools and technologies required to run these codes
> > as
> > well.
> > 
> > Thanking you in anticipation.
> > 
> > Regards!
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/czxttkl/MetaData/issues/9
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/czxttkl/MetaData/issues/9#issuecomment-215082734

## 

السلام علیکم ورحمۃ اللہ وبرکاتہ

Kind Regards!
Malik Khizer Hayat

**Comment by czxttkl** [comment]
Hello Malik,

Please find the source code attached. I hope it can still compile...

You need to use gradle to rebuild the project. You also need to rewrite
PaperCollector Class. Previously, we implemented it to collect paper
information from a mongodb.

Let me know if you have questions during restoring the project.

Thanks,
Chen

**Comment by malikhizar** [comment]
Thanks Chen,

For your response. I didn't find the attachment in the email I received. Also can you please provide the link for gradle? 
Is it an integrated development environment, all java and c# codes executed here in the same environment ?
Also please provide the data preparation steps because I have my own data to run within this project.

Thanks,
Khizar

**Comment by czxttkl** [comment]
Can you give me your real email address? I guess I am replying to github
proxy so that the attachment is lost.

Gradle is a tool to manage java libraries:
http://gradle.org/getting-started-gradle-java/  You should see a file named
"build.gradle" in the root directory of the attachment.

You probably need to read the source code of PaperCollector.java to check
how to prepare your own data.

**Comment by malikhizar** [comment]
khizerhayat92@gmail.com

This is my real email address. 

Is this also contain your data, if I want to run this on your data to see the results, would I be able to do this ?

**Comment by czxttkl** [comment]
Is this also contain your data, if I want to run this on your data to see
the results, would I be able to do this ?
I am afraid the answer is no.

**Comment by malikhizar** [comment]
Anyways, its ok. I have received your sent attachment i.e. "metadata". I'm seeing that it contains only java code, whereas clustering/c# code also included in the old version of project. 
Is this the complete code for EvoNetClus? Should I only have to run "build.gradle" file?

**Comment by czxttkl** [comment]
C# code should not be used anymore. The java version should be self
complete.

I guess you need to run build.grade to get java dependencies. Then, try to
check TestEvoNetworkFourAreaMT.java for example.

**Comment by malikhizar** [comment]
Okay I'll do as you suggested and let you know if further help required.
Your gratitude.

**Comment by malikhizar** [comment]
Hi Chen,

I have gone through all of your project. it seemed that all of this project is implemented according to your data input, whereas the data is not available within the project. So if I want to use my own data, I might think that I have to rewrite the most of the code files because of change in Target and Attribute objects.
I mean to say that if the data is available within the project, so that I can test your results and also I might replace your data with my own data (i.e. Target and Attribute objects) to get my own results but unfortunately I'm not getting what and how to use this project.
So how will your project (code) be reusable by the way?

**Comment by malikhizar** [comment]
Hi Chen,

While compiling "build.gradle" file, I have found the following error:

"file or directory '/home/limbartech/Downloads/malik/metadata/src/main/java', not found
Compiling with JDK Java compiler API"

Please help out how to handle this.

Thanks

**Comment by malikhizar** [comment]
Please help in this regard How can I use this project? Is it really useful for others if it is on github forum?

Thanking you in anticipation.

Regards
Khizar

**Comment by malikhizar** [comment]
Hi Chen,

You haven't posted anything after that? Is nothing suitable available with you ?

**Comment by malikhizar** [comment]
Hi Chen, 

I've translated your project into C# as a whole. I've compiled and ran it but the results are not so much as desired as I'm getting individual clusters for almost each of the target object. Whereas I've "Authors" as the target objects and (Papers, CoAuthors, Venues) as attribute objects. 

Moreover I'm sending you the code with data in .sql form. Please review it and update me about the results. Whether these results are desirable or is there some issue with the project?  

I'll upload my project at my github account. https://github.com/khizer-hayat/EvoNetClus
